// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject

package di

import (
	aiApi "github.com/GoSimplicity/CloudOps/internal/ai/api"
	aiDao "github.com/GoSimplicity/CloudOps/internal/ai/dao"
	aiService "github.com/GoSimplicity/CloudOps/internal/ai/service"
	"github.com/GoSimplicity/CloudOps/internal/ai/vector"
	k8sApi "github.com/GoSimplicity/CloudOps/internal/k8s/api"
	k8sClient "github.com/GoSimplicity/CloudOps/internal/k8s/client"
	k8sDao "github.com/GoSimplicity/CloudOps/internal/k8s/dao"
	k8sService "github.com/GoSimplicity/CloudOps/internal/k8s/service"
	promApi "github.com/GoSimplicity/CloudOps/internal/prometheus/api"
	promDao "github.com/GoSimplicity/CloudOps/internal/prometheus/dao"
	promService "github.com/GoSimplicity/CloudOps/internal/prometheus/service"
	"github.com/GoSimplicity/CloudOps/internal/startup"
	systemApi "github.com/GoSimplicity/CloudOps/internal/system/api"
	systemDao "github.com/GoSimplicity/CloudOps/internal/system/dao"
	systemService "github.com/GoSimplicity/CloudOps/internal/system/service"
	workorderApi "github.com/GoSimplicity/CloudOps/internal/workorder/api"
	workorderDao "github.com/GoSimplicity/CloudOps/internal/workorder/dao"
	workorderService "github.com/GoSimplicity/CloudOps/internal/workorder/service"
	ijwt "github.com/GoSimplicity/CloudOps/pkg/jwt"
	"github.com/gin-gonic/gin"
)

func InitApp() (*gin.Engine, *startup.ApplicationBootstrap, error) {
	// Infra
	logger := InitLogger()
	db := InitDB()
	rdb := InitRedis()
	enforcer := InitCasbin()
	jwtHandler := ijwt.NewJWTHandler(rdb)

	// System DAOs
	userDAO := systemDao.NewUserDAO(db, logger)
	roleDAO := systemDao.NewRoleDAO(db, logger)
	menuDAO := systemDao.NewMenuDAO(db, logger)

	// System Services
	userSvc := systemService.NewUserService(userDAO, roleDAO, jwtHandler, logger)
	roleSvc := systemService.NewRoleService(roleDAO, menuDAO, logger)
	menuSvc := systemService.NewMenuService(menuDAO, logger)

	// System Handlers
	userHdl := systemApi.NewUserHandler(userSvc)
	roleHdl := systemApi.NewRoleHandler(roleSvc)
	menuHdl := systemApi.NewMenuHandler(menuSvc)

	// K8s
	k8sClientInst := k8sClient.NewK8sClient(logger)
	clusterDAO := k8sDao.NewClusterDAO(db, logger)
	clusterSvc := k8sService.NewClusterService(clusterDAO, k8sClientInst, logger)
	nsSvc := k8sService.NewNamespaceService(k8sClientInst, logger)
	deploySvc := k8sService.NewDeploymentService(k8sClientInst, logger)
	podSvc := k8sService.NewPodService(k8sClientInst, logger)
	svcService := k8sService.NewServiceService(k8sClientInst, logger)
	cmSvc := k8sService.NewConfigMapService(k8sClientInst, logger)

	clusterHdl := k8sApi.NewK8sClusterHandler(clusterSvc)
	nsHdl := k8sApi.NewK8sNamespaceHandler(nsSvc)
	deployHdl := k8sApi.NewK8sDeploymentHandler(deploySvc)
	podHdl := k8sApi.NewK8sPodHandler(podSvc)
	svcHdl := k8sApi.NewK8sSvcHandler(svcService)
	cmHdl := k8sApi.NewK8sConfigMapHandler(cmSvc)

	// Prometheus DAOs
	scrapePoolDAO := promDao.NewScrapePoolDAO(db, logger)
	alertRuleDAO := promDao.NewAlertRuleDAO(db, logger)
	alertEventDAO := promDao.NewAlertEventDAO(db, logger)
	sendGroupDAO := promDao.NewSendGroupDAO(db, logger)

	// Prometheus Services
	scrapePoolSvc := promService.NewScrapePoolService(scrapePoolDAO, logger)
	alertRuleSvc := promService.NewAlertRuleService(alertRuleDAO, logger)
	alertEventSvc := promService.NewAlertEventService(alertEventDAO, sendGroupDAO, logger)
	sendGroupSvc := promService.NewSendGroupService(sendGroupDAO, logger)

	// Prometheus Handlers
	scrapePoolHdl := promApi.NewScrapePoolHandler(scrapePoolSvc)
	alertRuleHdl := promApi.NewAlertRuleHandler(alertRuleSvc)
	alertEventHdl := promApi.NewAlertEventHandler(alertEventSvc)
	sendGroupHdl := promApi.NewSendGroupHandler(sendGroupSvc)

	// Workorder DAOs
	templateDAO := workorderDao.NewTemplateDAO(db, logger)
	instanceDAO := workorderDao.NewInstanceDAO(db, logger)
	flowDAO := workorderDao.NewFlowDAO(db, logger)
	commentDAO := workorderDao.NewCommentDAO(db, logger)

	// Workorder Services
	templateSvc := workorderService.NewTemplateService(templateDAO, logger)
	instanceSvc := workorderService.NewInstanceService(instanceDAO, logger)
	flowSvc := workorderService.NewFlowService(flowDAO, instanceDAO, logger)
	commentSvc := workorderService.NewCommentService(commentDAO, logger)

	// Workorder Handlers
	templateHdl := workorderApi.NewTemplateHandler(templateSvc)
	instanceHdl := workorderApi.NewInstanceHandler(instanceSvc)
	flowHdl := workorderApi.NewFlowHandler(flowSvc)
	commentHdl := workorderApi.NewCommentHandler(commentSvc)

	// AI
	vecStore := vector.NewStore(logger)
	knowledgeDAO := aiDao.NewKnowledgeDAO(db, logger)
	llmSvc := aiService.NewLLMService(logger)
	ragSvc := aiService.NewRAGService(llmSvc, knowledgeDAO, vecStore, logger)
	aiHdl := aiApi.NewAIHandler(ragSvc)

	// Middlewares & Engine
	middlewares := InitMiddlewares(jwtHandler, logger, enforcer)
	engine := InitGinServer(
		middlewares,
		userHdl, roleHdl, menuHdl,
		clusterHdl, nsHdl, deployHdl, podHdl, svcHdl, cmHdl,
		scrapePoolHdl, alertRuleHdl, alertEventHdl, sendGroupHdl,
		templateHdl, instanceHdl, flowHdl, commentHdl,
		aiHdl,
	)

	bootstrap := startup.NewApplicationBootstrap(ragSvc, logger)
	return engine, bootstrap, nil
}
